In [1]:
import numpy as np
lf=[]
n=int(input("enter a number of element:"))
for i in range(0,n):
    ele=int(input())
    lf.append(ele)
    
print(lf)
arr=np.array(lf)
arr=np.sort(arr)
print("sorted array={}".format(arr))
ele=int(input("enter the value to search"))
i=np.where(arr==ele)
print("index={}".format(i))
s=int(input("enter spliting value:"))
narr=np.array_split(arr,s)
print(narr)

enter a number of element:2
2
3
[2, 3]
sorted array=[2 3]
enter the value to search1
index=(array([], dtype=int64),)
enter spliting value:2
[array([2]), array([3])]


## 

In [2]:
import numpy as np
from numpy import array,argmin,sqrt,sum
obs=array([111.0,188.0])

code=array([[10.0,203.0],[132.0,193.0],[145.0,155.0],[57.0,175.0]])
diff=code-obs
dist=sqrt(sum(diff**2,axis=-1))
print(obs,obs.shape)
print(code,code.shape)
print(diff,diff.shape)
print(dist,dist.shape)
argmin(dist)


[111. 188.] (2,)
[[ 10. 203.]
 [132. 193.]
 [145. 155.]
 [ 57. 175.]] (4, 2)
[[-101.   15.]
 [  21.    5.]
 [  34.  -33.]
 [ -54.  -13.]] (4, 2)
[102.10778619  21.58703314  47.38143096  55.54277631] (4,)


1